# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ccc9322e0b265be2702af8ebab1385e3ce8a9b8d356f089a2f8a443aa0e4220070909cdad3483020198cd68f68f92f3e8f1293cf2e42770e12327eb01a6a5af5

test:
  secret_key_base: 60ff38d840ca823504395fa7622af70774cc4e37869add4b952ff32ecbe3b1358119f78e6690756f4de049aa97464c1ebb3df0d282f4baf7a3f6ad7a94b9ab5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
